Audit Turnaround Time things
eastgenomics/themis pull request #1
Opened 2022-09-06 11:00 UTC by rklocke

- Queries DNAnexus to get all 002 projects for each assay in specified time period
- Finds the time the log file (or first file for SNP runs) was uploaded, time first job was run in the 002 project and the time last MultiQC job was run
- Finds Jira tickets for those runs (in both open and closed sequencing runs ticket queues) and if ticket has All Samples Released gets time ticket was resolved. If open ticket calculates time On Hold or at Urgent Samples Released
- Rescues and shows any Jira run tickets with no 002 project found
- Rescues and shows any run tickets where the run was not completed (resolved but data not released)
- Shows runs where manual review is required (e.g. one of the timings was not found, timings don't make sense)
- Shows where there were mismatches between Jira ticket names and 002 projects or 002 project names and Staging Area run folder names (if within 1-2 differences)
- Creates HTML file with a plot and stats table for each assay type and the flagged runs
- Creates CSV with the underlying data for each step and the time between each step

2022-09-06 11:00 UTC, pep8speaks commented
Hello @rklocke! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`tests/test_TAT_queries.py`](https://github.com/eastgenomics/themis/blob/eb96807d9baf0f146eb6d7f63f752a47b9ba2590/tests/test_TAT_queries.py):

> [Line 13:1](https://github.com/eastgenomics/themis/blob/eb96807d9baf0f146eb6d7f63f752a47b9ba2590/tests/test_TAT_queries.py#L13): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 19:1](https://github.com/eastgenomics/themis/blob/eb96807d9baf0f146eb6d7f63f752a47b9ba2590/tests/test_TAT_queries.py#L19): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 26:9](https://github.com/eastgenomics/themis/blob/eb96807d9baf0f146eb6d7f63f752a47b9ba2590/tests/test_TAT_queries.py#L26): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 27:9](https://github.com/eastgenomics/themis/blob/eb96807d9baf0f146eb6d7f63f752a47b9ba2590/tests/test_TAT_queries.py#L27): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 29:9](https://github.com/eastgenomics/themis/blob/eb96807d9baf0f146eb6d7f63f752a47b9ba2590/tests/test_TAT_queries.py#L29): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 30:9](https://github.com/eastgenomics/themis/blob/eb96807d9baf0f146eb6d7f63f752a47b9ba2590/tests/test_TAT_queries.py#L30): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 31:9](https://github.com/eastgenomics/themis/blob/eb96807d9baf0f146eb6d7f63f752a47b9ba2590/tests/test_TAT_queries.py#L31): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 32:9](https://github.com/eastgenomics/themis/blob/eb96807d9baf0f146eb6d7f63f752a47b9ba2590/tests/test_TAT_queries.py#L32): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 33:9](https://github.com/eastgenomics/themis/blob/eb96807d9baf0f146eb6d7f63f752a47b9ba2590/tests/test_TAT_queries.py#L33): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 34:9](https://github.com/eastgenomics/themis/blob/eb96807d9baf0f146eb6d7f63f752a47b9ba2590/tests/test_TAT_queries.py#L34): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 36:9](https://github.com/eastgenomics/themis/blob/eb96807d9baf0f146eb6d7f63f752a47b9ba2590/tests/test_TAT_queries.py#L36): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 37:9](https://github.com/eastgenomics/themis/blob/eb96807d9baf0f146eb6d7f63f752a47b9ba2590/tests/test_TAT_queries.py#L37): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 38:9](https://github.com/eastgenomics/themis/blob/eb96807d9baf0f146eb6d7f63f752a47b9ba2590/tests/test_TAT_queries.py#L38): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 39:9](https://github.com/eastgenomics/themis/blob/eb96807d9baf0f146eb6d7f63f752a47b9ba2590/tests/test_TAT_queries.py#L39): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 40:9](https://github.com/eastgenomics/themis/blob/eb96807d9baf0f146eb6d7f63f752a47b9ba2590/tests/test_TAT_queries.py#L40): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 41:9](https://github.com/eastgenomics/themis/blob/eb96807d9baf0f146eb6d7f63f752a47b9ba2590/tests/test_TAT_queries.py#L41): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 43:9](https://github.com/eastgenomics/themis/blob/eb96807d9baf0f146eb6d7f63f752a47b9ba2590/tests/test_TAT_queries.py#L43): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 44:9](https://github.com/eastgenomics/themis/blob/eb96807d9baf0f146eb6d7f63f752a47b9ba2590/tests/test_TAT_queries.py#L44): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 45:9](https://github.com/eastgenomics/themis/blob/eb96807d9baf0f146eb6d7f63f752a47b9ba2590/tests/test_TAT_queries.py#L45): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 46:9](https://github.com/eastgenomics/themis/blob/eb96807d9baf0f146eb6d7f63f752a47b9ba2590/tests/test_TAT_queries.py#L46): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 47:9](https://github.com/eastgenomics/themis/blob/eb96807d9baf0f146eb6d7f63f752a47b9ba2590/tests/test_TAT_queries.py#L47): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 48:9](https://github.com/eastgenomics/themis/blob/eb96807d9baf0f146eb6d7f63f752a47b9ba2590/tests/test_TAT_queries.py#L48): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 72:1](https://github.com/eastgenomics/themis/blob/eb96807d9baf0f146eb6d7f63f752a47b9ba2590/tests/test_TAT_queries.py#L72): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 76:9](https://github.com/eastgenomics/themis/blob/eb96807d9baf0f146eb6d7f63f752a47b9ba2590/tests/test_TAT_queries.py#L76): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 77:9](https://github.com/eastgenomics/themis/blob/eb96807d9baf0f146eb6d7f63f752a47b9ba2590/tests/test_TAT_queries.py#L77): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 79:9](https://github.com/eastgenomics/themis/blob/eb96807d9baf0f146eb6d7f63f752a47b9ba2590/tests/test_TAT_queries.py#L79): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 80:9](https://github.com/eastgenomics/themis/blob/eb96807d9baf0f146eb6d7f63f752a47b9ba2590/tests/test_TAT_queries.py#L80): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 81:9](https://github.com/eastgenomics/themis/blob/eb96807d9baf0f146eb6d7f63f752a47b9ba2590/tests/test_TAT_queries.py#L81): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 83:9](https://github.com/eastgenomics/themis/blob/eb96807d9baf0f146eb6d7f63f752a47b9ba2590/tests/test_TAT_queries.py#L83): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 84:9](https://github.com/eastgenomics/themis/blob/eb96807d9baf0f146eb6d7f63f752a47b9ba2590/tests/test_TAT_queries.py#L84): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 85:9](https://github.com/eastgenomics/themis/blob/eb96807d9baf0f146eb6d7f63f752a47b9ba2590/tests/test_TAT_queries.py#L85): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 87:9](https://github.com/eastgenomics/themis/blob/eb96807d9baf0f146eb6d7f63f752a47b9ba2590/tests/test_TAT_queries.py#L87): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 88:9](https://github.com/eastgenomics/themis/blob/eb96807d9baf0f146eb6d7f63f752a47b9ba2590/tests/test_TAT_queries.py#L88): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 89:9](https://github.com/eastgenomics/themis/blob/eb96807d9baf0f146eb6d7f63f752a47b9ba2590/tests/test_TAT_queries.py#L89): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual  [...]

2022-09-06 13:48 UTC, jethror1 requested changes
could you format the repo something like here: https://github.com/eastgenomics/Haemonc_requests

so create a folder for all of this something like `TAT_audit`, a brief description of what it is in the table in the main readme, then a read me in this folder to explain what the script does and how to run it etc please

> Reviewed 3 of 7 files at r1, 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/themis/1#-:-NBI2JwkD3V0k1Z5fDAo:b-p3xx83)* status: 4 of 7 files reviewed, 16 unresolved discussions (waiting on @jethror1 and @rklocke)

___
*[`templates/audit_template.html` line 15 at r2](https://reviewable.io/reviews/eastgenomics/themis/1#-NBHrUFg5P7dusQuiW63:-NBHrUFh3frFTUaoq-SX:bwbajah) ([raw file](https://github.com/eastgenomics/themis/blob/d20a2241145875da2f2657d889f0fb64f2d51d3b/templates/audit_template.html#L15)):*
> ```HTML
>     <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css">
> 	  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/scroller/2.0.3/css/scroller.dataTables.min.css">
> 	  <link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap5.min.js">
> ```

indented too much



_Code quote:_
```HTML
	  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/scroller/2.0.3/css/scroller.dataTables.min.css">
	  <link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap5.min.js">
```
___
*[`templates/audit_template.html` line 25 at r2](https://reviewable.io/reviews/eastgenomics/themis/1#-NBHrXP504T7wVj59JTR:-NBHrXP504T7wVj59JTS:bd5d6lg) ([raw file](https://github.com/eastgenomics/themis/blob/d20a2241145875da2f2657d889f0fb64f2d51d3b/templates/audit_template.html#L25)):*
> ```HTML
>     <script type="text/javascript" language="javascript" src="https://cdn.datatables.net/plug-ins/1.10.25/features/pageResize/dataTables.pageResize.min.js"></script>
>     <script type="text/javascript" src="https://cdn.datatables.net/buttons/2.2.2/js/dataTables.buttons.min.js"></script>
>     <script type="text/javascript" src="https://cdn.datatables.net/buttons/2.2.2/js/buttons.html5.min.js"></script>
> ```

indentation



_Code quote:_
```HTML
    <script type="text/javascript" language="javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script>
	  <script type="text/javascript" language="javascript" src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" language="javascript" src="https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap5.min.js"></script>
	  <script type="text/javascript" language="javascript" src="https://cdn.datatables.net/scroller/2.0.3/js/dataTables.scroller.min.js"></script>
    <script type="text/javascript" language="javascript" src="https://cdn.datatables.net/plug-ins/1.10.25/features/pageResize/dataTables.pageResize.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/2.2.2/js/dataTables.buttons.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/2.2.2/js/buttons.html5.min.js"></script>
```
___
*[`utils/TAT_queries.py` line 219 at r2](https://reviewable.io/reviews/eastgenomics/themis/1#-NBHtCj6EUjy7EX1uqA2:-NBHtCj6EUjy7EX1uqA3:b-slq7yp) ([raw file](https://github.com/eastgenomics/themis/blob/d20a2241145875da2f2657d889f0fb64f2d51d3b/utils/TAT_queries.py#L219)):*
> ```Python
>     """
>     if assay_type == 'SNP':
>         # The files are within the named folder
> ```

can you add to this comment that this is because SNP runs are currently done on the miseq and manually uploaded and not handled via dx-streaming-upload



_Code quote:_
```Python
The files are within the named folder
```
___
*[`utils/TAT_queries.py` line 229 at r2](https://reviewable.io/reviews/eastgenomics/themis/1#-NBHtbCnDKOHiI4VjfPW:-NBHtbCnDKOHiI4VjfPX:bf3c8ny) ([raw file](https://github.com/eastgenomics/themis/blob/d20a2241145875da2f2657d889f0fb64f2d51d3b/utils/TAT_queries.py#L229)):*
> ```Python
>     # If issues uploading to StagingArea
>     # The real log file is in processed/ folder
>     if log_file_bug:
> ```

how is this determined? I'm sure I'll find it further down but adding this so I understand



_Code quote:_
```Python
if log_file_bug:
```
___
*[`utils/TAT_queries.py` line 502 at r2](https://reviewable.io/reviews/eastgenomics/themis/1#-NBHvojf-M_pnDH-vMyE:-NBHvojf-M_pnDH-vMyF:bb7o4ux) ([raw file](https://github.com/eastgenomics/themis/blob/d20a2241145875da2f2657d889f0fb64f2d51d3b/utils/TAT_queries.py#L502)):*
> ```Python
>     Creates a nested dict with all relevant info for an assay type
>     using the other functions
>     run
> ```

run?



_Code quote:_
```Python
run
```
___
*[`utils/TAT_queries.py` line 522 at r2](https://reviewable.io/reviews/eastgenomics/themis/1#-NBHvz86924h6SyqwfTG:-NBHvz86924h6SyqwfTH:b70l3lh) ([raw file](https://github.com/eastgenomics/themis/blob/d20a2241145875da2f2657d889f0fb64f2d51d3b/utils/TAT_queries.py#L522)):*
> ```Python
>     )
>     assay_run_dict = add_successful_multiqc_time(assay_run_dict)
>     find_earliest_002_job(assay_run_dict)
> ```

should this function not be returning something?



_Code quote:_
```Python
find_earliest_002_job(assay_run_dict)
```
___
*[`utils/TAT_queries.py` line 565 at r2](https://reviewable.io/reviews/eastgenomics/themis/1#-NBHwNBy-pAFKsVgusm-:-NBHwNBy-pAFKsVgusm0:b-u6f35x) ([raw file](https://github.com/eastgenomics/themis/blob/d20a2241145875da2f2657d889f0fb64f2d51d3b/utils/TAT_queries.py#L565)):*
> ```Python
>         new_data = json.loads(queue_response.text)['values']
>         response_data += new_data
>         start += page_size
> ```

are start and page_size used?



_Code quote:_
```Python
start += page_size
```
___
*[`utils/TAT_queries.py` line 593 at r2](https://reviewable.io/reviews/eastgenomics/themis/1#-NBHwZ5e4tEV5E5g6Uck:-NBHwZ5e4tEV5E5g6Ucl:b32vbm) ([raw file](https://github.com/eastgenomics/themis/blob/d20a2241145875da2f2657d889f0fb64f2d51d3b/utils/TAT_queries.py#L593)):*
> ```Python
> def get_closest_match_in_dict(ticket_name, my_dict):
>     """
>     Checks for run names in the dict that are only off by 1 character
> ```

2?



_Code quote:_
```Python
1 
```
___
*[`utils/TAT_queries.py` line 619 at r2](https://reviewable.io/reviews/eastgenomics/themis/1#-NBHxEA6DoJxQgpAm2Qr:-NBHxEA6DoJxQgpAm2Qs:b-uo3hvo) ([raw file](https://github.com/eastgenomics/themis/blob/d20a2241145875da2f2657d889f0fb64f2d51d3b/utils/TAT_queries.py#L619)):*
> ```Python
>         if distance <= 2:
>             closest_key_in_dict = key
>             if distance > 0:
> ```

could this just be:
```
if distance in [1, 2]:
    closest_key_in_dict = key
    typo_ticket_info = {
            'jira_ticket_name': ticket_name,
            'project_name_002': closest_key_in_dict,
            'assay_type': my_dict[closest_key_in_dict]['assay_type']
        }
```



_Code quote:_
```Python
        if distance <= 2:
            closest_key_in_dict = key
            if distance > 0:
                typo_ticket_info = {
                    'jira_ticket_name': ticket_name,
                    'project_name_002': closest_key_in_dict,
                    'assay_type': my_dict[closest_key_in_dict]['assay_type']
                }
```
___
*[`utils/TAT_queries.py` line 775 at r2](https://reviewable.io/reviews/eastgenomics/themis/1#-NBHyAJ82GLjaw23H81a:-NBHyAJ82GLjaw23H81b:bi2u686) ([raw file](https://github.com/eastgenomics/themis/blob/d20a2241145875da2f2657d889f0fb64f2d51d3b/utils/TAT_queries.py#L775)):*
> ```Python
>                             })
>                     else:
>                         # Data not released, add to cancelled list
> ```

will / should the urgents  only status be in here? or is it handled?



_Code quote:_
```Python
 Data not released, add to cancelled list
```
___
*[`utils/TAT_queries.py` line 791 at r2](https://reviewable.io/reviews/eastgeno [...]

2022-09-07 08:04 UTC, rklocke reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/themis/1)* status: 0 of 11 files reviewed, 16 unresolved discussions (waiting on @jethror1)

___
*[`templates/audit_template.html` line 15 at r2](https://reviewable.io/reviews/eastgenomics/themis/1#-NBHrUFg5P7dusQuiW63:-NBI4Oai07aBT0bO23_J:b-896fix) ([raw file](https://github.com/eastgenomics/themis/blob/d20a2241145875da2f2657d889f0fb64f2d51d3b/templates/audit_template.html#L15)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

indented too much
</blockquote></details>

Done.
___
*[`templates/audit_template.html` line 25 at r2](https://reviewable.io/reviews/eastgenomics/themis/1#-NBHrXP504T7wVj59JTR:-NBI4QkL7GrU-xfMv8XB:b-896fix) ([raw file](https://github.com/eastgenomics/themis/blob/d20a2241145875da2f2657d889f0fb64f2d51d3b/templates/audit_template.html#L25)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

indentation
</blockquote></details>

Done.
___
*[`utils/TAT_queries.py` line 219 at r2](https://reviewable.io/reviews/eastgenomics/themis/1#-NBHtCj6EUjy7EX1uqA2:-NBI58Y025zwrXriKFhj:b-896fix) ([raw file](https://github.com/eastgenomics/themis/blob/d20a2241145875da2f2657d889f0fb64f2d51d3b/utils/TAT_queries.py#L219)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

can you add to this comment that this is because SNP runs are currently done on the miseq and manually uploaded and not handled via dx-streaming-upload
</blockquote></details>

Done.
___
*[`utils/TAT_queries.py` line 229 at r2](https://reviewable.io/reviews/eastgenomics/themis/1#-NBHtbCnDKOHiI4VjfPW:-NBI5FCu3vVEavYA-Be2:b-q1dcqy) ([raw file](https://github.com/eastgenomics/themis/blob/d20a2241145875da2f2657d889f0fb64f2d51d3b/utils/TAT_queries.py#L229)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

how is this determined? I'm sure I'll find it further down but adding this so I understand
</blockquote></details>

In the add_log_file_time() function, the time of the log file upload to Staging Area is checked and if it is after the earliest 002 job for that run, it deems it a bug and calls the find_files_in_folder() function with the log_file_bug arg set to True



_Code snippet:_
```Python
# If log file was uploaded before the first 002 job
# Add in log file upload time
if upload_time < run_dict[run_name]['earliest_002_job']:
   run_dict[run_name]['upload_time'] = upload_time

# Else, if log file upload is after earliest 002 job
# Go into the processed folder + get log time instead
else:
   log_file_info = find_files_in_folder(
      run_name, assay_type, True
   )
```
___
*[`utils/TAT_queries.py` line 502 at r2](https://reviewable.io/reviews/eastgenomics/themis/1#-NBHvojf-M_pnDH-vMyE:-NBI6-t65lHC51ElzWep:b-896fix) ([raw file](https://github.com/eastgenomics/themis/blob/d20a2241145875da2f2657d889f0fb64f2d51d3b/utils/TAT_queries.py#L502)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

run?
</blockquote></details>

Done.
___
*[`utils/TAT_queries.py` line 522 at r2](https://reviewable.io/reviews/eastgenomics/themis/1#-NBHvz86924h6SyqwfTG:-NBI61Gh9Y_WdOOTdGyJ:b-pi2941) ([raw file](https://github.com/eastgenomics/themis/blob/d20a2241145875da2f2657d889f0fb64f2d51d3b/utils/TAT_queries.py#L522)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

should this function not be returning something?
</blockquote></details>

it updates the dict directly (not a copy of it) so I don't rewrite the variable. Is that a bad way to do things?
___
*[`utils/TAT_queries.py` line 565 at r2](https://reviewable.io/reviews/eastgenomics/themis/1#-NBHwNBy-pAFKsVgusm-:-NBI6EroAPJZHU227J5l:b4bglau) ([raw file](https://github.com/eastgenomics/themis/blob/d20a2241145875da2f2657d889f0fb64f2d51d3b/utils/TAT_queries.py#L565)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

are start and page_size used?
</blockquote></details>

yep the start is updated by 50 each time (page size) and added on to the end of the url to get the response from the next page. I've changed this to base_url so it's clearer:



_Code snippet:_
```Python
url=f"{base_url}?start={start}"
```
___
*[`utils/TAT_queries.py` line 593 at r2](https://reviewable.io/reviews/eastgenomics/themis/1#-NBHwZ5e4tEV5E5g6Uck:-NBI7-JC1WIz0NmoC4CI:b-896fix) ([raw file](https://github.com/eastgenomics/themis/blob/d20a2241145875da2f2657d889f0fb64f2d51d3b/utils/TAT_queries.py#L593)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

2?
</blockquote></details>

Done.
___
*[`utils/TAT_queries.py` line 619 at r2](https://reviewable.io/reviews/eastgenomics/themis/1#-NBHxEA6DoJxQgpAm2Qr:-NBI7EIA4Mz7PSleyIz3:b-cuktok) ([raw file](https://github.com/eastgenomics/themis/blob/d20a2241145875da2f2657d889f0fb64f2d51d3b/utils/TAT_queries.py#L619)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

could this just be:
```
if distance in [1, 2]:
    closest_key_in_dict = key
    typo_ticket_info = {
            'jira_ticket_name': ticket_name,
            'project_name_002': closest_key_in_dict,
            'assay_type': my_dict[closest_key_in_dict]['assay_type']
        }
```
</blockquote></details>

I tried this and it broke everything, if the ticket and the dictionary key name (run name from 002 project) are exactly the same (0 distance), or 1 or 2 distance I want them to be treated the same and the relevant run name to be the match
But then only if it's a mismatch (distance > 0), I want to add it to create the typo_ticket_info dict to be flagged. Is there a better way to do that?
___
*[`utils/TAT_queries.py` line 775 at r2](https://reviewable.io/reviews/eastgenomics/themis/1#-NBHyAJ82GLjaw23H81a:-NBI7IVV0UNaB7dSWuot:b3l5hw8) ([raw file](https://github.com/eastgenomics/themis/blob/d20a2241145875da2f2657d889f0fb64f2d51d3b/utils/TAT_queries.py#L775)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

will / should the urgents  only status be in here? or is it handled?
</blockquote></details>

If a ticket has status 'Urgent samples released' it is not in this Jira ticket queue (closed sequencing runs), so I get them with a separate function from a different API response (add_jira_info_open_issues())
___
*[`utils/TAT_queries.py` line 791 at r2](https://reviewable.io/reviews/eastgenomics/themis/1#-NBHyM7z4ii_dN67-vad:-NBICnf47UKZzu_jrVIO:b-5g96rs) ([raw file](https://github.com/eastgenomics/themis/blob/d20a2241145875da2f2657d889f0fb64f2d51d3b/utils/TAT_queries.py#L791)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

catching any exception and passing it not particular robust and can lead to really hard to debug issues, what is it you're expecting could be raised? can you handle what you expect and is appropriate to pass, and anything else handle separately or exit on? considering you have some querying in here,  if the Jira API was off for an amount of time these runs would be wrongly skipped, right?
</blockquote></details>

I was using this because one run ticket didn't seem to have the relevant key for assay type. I tried to work out a good except but changed this to use .get() which I think makes more sense, and means I can just set it to 'Unknown' if the key doesn't exist.
___
*[`utils/TAT_queries.py` line 898 at r2](https://reviewable.io/reviews/eastgenomics/themis/1#-NBHz0G98AsJoOjC45PU:-NBI8DfrB_on1Uvw4XA9:b-896fix) ([raw file](https://github.com/eastgenomics/themis/blob/d20a2241145875da2f2657d889f0fb64f2d51d3b/utils/TAT_queries.py#L898)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

a super tiny probably just my brain thing but I find it confusing in docstrings/comments when the continuing line is capitalised when it isn't a new sentence, as in :
```
Adds columns to the df for log file to earliest 002 job
And bioinfo processing time
```

vs

```
Adds columns to the df for log file to  [...]

2022-09-07 08:52 UTC, jethror1 requested changes
> Reviewed 8 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/themis/1)* status: 8 of 11 files reviewed, 8 unresolved discussions (waiting on @jethror1 and @rklocke)

___
*[`README.md` line 3 at r3](https://reviewable.io/reviews/eastgenomics/themis/1#-NBM5Mmt-7JN1XSnxncp:-NBM5Mmt-7JN1XSnxncq:b-hz7kd8) ([raw file](https://github.com/eastgenomics/themis/blob/85e8b21c90219e0595e4d0ef7b5db7adedd9732f/README.md#L3)):*
> ```Markdown
> # themis
> 
> Repository for code related to automated auditing.
> ```

not really automated, can this be `bioinformatics internal auditing` pls



_Code quote:_
```Markdown
automated
```
___
*[`TAT_audit/README.md` line 1 at r3](https://reviewable.io/reviews/eastgenomics/themis/1#-NBM5W628sQiGniMBLHS:-NBM5W628sQiGniMBLHT:b8qhn21) ([raw file](https://github.com/eastgenomics/themis/blob/85e8b21c90219e0595e4d0ef7b5db7adedd9732f/TAT_audit/README.md#L1)):*
> ```Markdown
> # TAT_audit
> ```

could the title just be `Turn around times`?



_Code quote:_
```Markdown
TAT_audit
```
___
*[`TAT_audit/README.md` line 2 at r3](https://reviewable.io/reviews/eastgenomics/themis/1#-NBM5j-W35KoyJ40O6nd:-NBM5j-W35KoyJ40O6ne:bekqgqs) ([raw file](https://github.com/eastgenomics/themis/blob/85e8b21c90219e0595e4d0ef7b5db7adedd9732f/TAT_audit/README.md#L2)):*
> ```Markdown
> # TAT_audit
> This repo contains the script to run an automated audit to check the bioinformatics processing turnaround times (TAT) for our CEN, MYE, TWE, TSO500 and SNP services. 
> ```

to generate an audit summary report for



_Code quote:_
```Markdown
automated audit 
```
___
*[`TAT_audit/README.md` line 25 at r3](https://reviewable.io/reviews/eastgenomics/themis/1#-NBM5qzE1r6Sq-gXIYbV:-NBM5qzE1r6Sq-gXIYbW:b-u2m96i) ([raw file](https://github.com/eastgenomics/themis/blob/85e8b21c90219e0595e4d0ef7b5db7adedd9732f/TAT_audit/README.md#L25)):*
> ```Markdown
> The script works by:
> - Querying DNAnexus to find all of the 002 projects for each assay in the past specified number of weeks
> - Finding the time the log file was uploaded in Staging Area for that run (or the first file uploaded in Staging Area if a SNP run)
> ```

can you add a sub bullet point here on why SNP runs are handled differently so its obvious, one day it will change so this will need updating
___
*[`TAT_audit/utils/TAT_queries.py` line 742 at r3](https://reviewable.io/reviews/eastgenomics/themis/1#-NBM8QxPDLfo15A_buCl:-NBM8QxPDLfo15A_buCm:bh97653) ([raw file](https://github.com/eastgenomics/themis/blob/85e8b21c90219e0595e4d0ef7b5db7adedd9732f/TAT_audit/utils/TAT_queries.py#L742)):*
> ```Python
>             # Get relevant info
>             # Try and get the key which stores the assay type
>             # If 'SNP Genotyping' change to 'SNP'
> ```

 why change it?



_Code quote:_
```Python
# If 'SNP Genotyping' change to 'SNP'
```
___
*[`utils/TAT_queries.py` line 522 at r2](https://reviewable.io/reviews/eastgenomics/themis/1#-NBHvz86924h6SyqwfTG:-NBM6geW27JmMNtzgurt:b-g8d3xs) ([raw file](https://github.com/eastgenomics/themis/blob/d20a2241145875da2f2657d889f0fb64f2d51d3b/utils/TAT_queries.py#L522)):*
I'm pretty sure it isn't as you pass in the dict to the function, but don't capture what is returned, and since `assay_run_dict` is not a global or a class attribute the changes to it are only local to that function call and you aren't updating the variable with what is returned. 

Example:
```
>>> a=5
>>> def my_func(val):
...     return val+5
... 
>>> my_func(a)
10
>>> a
5
```

or am I wrong and is it working as you expect? 
___
*[`utils/TAT_queries.py` line 619 at r2](https://reviewable.io/reviews/eastgenomics/themis/1#-NBHxEA6DoJxQgpAm2Qr:-NBM7eAR6VTHu37RtDkw:b-tqv3nf) ([raw file](https://github.com/eastgenomics/themis/blob/d20a2241145875da2f2657d889f0fb64f2d51d3b/utils/TAT_queries.py#L619)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

I tried this and it broke everything, if the ticket and the dictionary key name (run name from 002 project) are exactly the same (0 distance), or 1 or 2 distance I want them to be treated the same and the relevant run name to be the match
But then only if it's a mismatch (distance > 0), I want to add it to create the typo_ticket_info dict to be flagged. Is there a better way to do that?
</blockquote></details>

ahh okay that makes sense, then what you have is fine as whatever I'd suggest would then only be using different operators but basically the same
___
*[`utils/TAT_queries.py` line 791 at r2](https://reviewable.io/reviews/eastgenomics/themis/1#-NBHyM7z4ii_dN67-vad:-NBM8U94ACRAbhDhxBlM:b7zczin) ([raw file](https://github.com/eastgenomics/themis/blob/d20a2241145875da2f2657d889f0fb64f2d51d3b/utils/TAT_queries.py#L791)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

I was using this because one run ticket didn't seem to have the relevant key for assay type. I tried to work out a good except but changed this to use .get() which I think makes more sense, and means I can just set it to 'Unknown' if the key doesn't exist.
</blockquote></details>

okay that makes sense, definitely better :) 


<!-- Sent from Reviewable.io -->

2022-09-07 12:43 UTC, rklocke reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/themis/1)* status: 7 of 11 files reviewed, 8 unresolved discussions (waiting on @jethror1)

___
*[`README.md` line 3 at r3](https://reviewable.io/reviews/eastgenomics/themis/1#-NBM5Mmt-7JN1XSnxncp:-NBMAwOk10BBeDZ3ck8h:b-896fix) ([raw file](https://github.com/eastgenomics/themis/blob/85e8b21c90219e0595e4d0ef7b5db7adedd9732f/README.md#L3)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

not really automated, can this be `bioinformatics internal auditing` pls
</blockquote></details>

Done.
___
*[`TAT_audit/README.md` line 1 at r3](https://reviewable.io/reviews/eastgenomics/themis/1#-NBM5W628sQiGniMBLHS:-NBMAvUj7TwDTSk_Pxqt:b-896fix) ([raw file](https://github.com/eastgenomics/themis/blob/85e8b21c90219e0595e4d0ef7b5db7adedd9732f/TAT_audit/README.md#L1)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

could the title just be `Turn around times`?
</blockquote></details>

Done.
___
*[`TAT_audit/README.md` line 2 at r3](https://reviewable.io/reviews/eastgenomics/themis/1#-NBM5j-W35KoyJ40O6nd:-NBMAvoj2LuClMq2oQe-:b-896fix) ([raw file](https://github.com/eastgenomics/themis/blob/85e8b21c90219e0595e4d0ef7b5db7adedd9732f/TAT_audit/README.md#L2)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

to generate an audit summary report for
</blockquote></details>

Done.
___
*[`TAT_audit/README.md` line 25 at r3](https://reviewable.io/reviews/eastgenomics/themis/1#-NBM5qzE1r6Sq-gXIYbV:-NBMAxPK1VSeawf4ILr4:b-896fix) ([raw file](https://github.com/eastgenomics/themis/blob/85e8b21c90219e0595e4d0ef7b5db7adedd9732f/TAT_audit/README.md#L25)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

can you add a sub bullet point here on why SNP runs are handled differently so its obvious, one day it will change so this will need updating
</blockquote></details>

Done.
___
*[`TAT_audit/utils/TAT_queries.py` line 742 at r3](https://reviewable.io/reviews/eastgenomics/themis/1#-NBM8QxPDLfo15A_buCl:-NBMBReM4H-cfh0lEtp1:bcmi8hm) ([raw file](https://github.com/eastgenomics/themis/blob/85e8b21c90219e0595e4d0ef7b5db7adedd9732f/TAT_audit/utils/TAT_queries.py#L742)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

 why change it?
</blockquote></details>

In the Jira tickets the SNP assay value is 'SNP Genotyping' but I change it to 'SNP' just so that I can check it easily against the ASSAY_TYPES I'm looking at:



_Code snippet:_
```Python
ASSAY_TYPES = ['TWE', 'CEN', 'MYE', 'TSO500', 'SNP']
```
___
*[`utils/TAT_queries.py` line 522 at r2](https://reviewable.io/reviews/eastgenomics/themis/1#-NBHvz86924h6SyqwfTG:-NBMEbne0XPk3QkGxukh:bkdnxgi) ([raw file](https://github.com/eastgenomics/themis/blob/d20a2241145875da2f2657d889f0fb64f2d51d3b/utils/TAT_queries.py#L522)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

I'm pretty sure it isn't as you pass in the dict to the function, but don't capture what is returned, and since `assay_run_dict` is not a global or a class attribute the changes to it are only local to that function call and you aren't updating the variable with what is returned. 

Example:
```
>>> a=5
>>> def my_func(val):
...     return val+5
... 
>>> my_func(a)
10
>>> a
5
```

or am I wrong and is it working as you expect? 
</blockquote></details>

It does seem to work as I expect but I have changed to assign it back to assay_run_dict anyway :) 
___
*[`utils/TAT_queries.py` line 619 at r2](https://reviewable.io/reviews/eastgenomics/themis/1#-NBHxEA6DoJxQgpAm2Qr:-NBM8vTYDiTDU8I0nf3e:b-896fix) ([raw file](https://github.com/eastgenomics/themis/blob/d20a2241145875da2f2657d889f0fb64f2d51d3b/utils/TAT_queries.py#L619)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

ahh okay that makes sense, then what you have is fine as whatever I'd suggest would then only be using different operators but basically the same
</blockquote></details>

Done.
___
*[`utils/TAT_queries.py` line 791 at r2](https://reviewable.io/reviews/eastgenomics/themis/1#-NBHyM7z4ii_dN67-vad:-NBMABnC2JfLUoN1qVAR:b-896fix) ([raw file](https://github.com/eastgenomics/themis/blob/d20a2241145875da2f2657d889f0fb64f2d51d3b/utils/TAT_queries.py#L791)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

okay that makes sense, definitely better :) 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-07 14:02 UTC, jethror1 approved these changes
> Reviewed 3 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/themis/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rklocke)



<!-- Sent from Reviewable.io -->

2022-09-07 14:05 UTC, merged