Dxapp compliance
eastgenomics/themis pull request #4
Opened 2022-11-04 17:50 UTC by RSWilson1

Added all api queries for audit performa.
Drafted jinja2 template.

To add next:
- datatables.
- plots of % compliance vs latest release date.
- other plots that could be helpful to visualise.

2022-11-07 12:50 UTC, jethror1 requested changes
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/themis/4)* status: 1 of 4 files reviewed, 14 unresolved discussions (waiting on @RSWilson1)

___
*[`dxapp_compliance/Access_file_GH.py` line 6 at r1](https://reviewable.io/reviews/eastgenomics/themis/4#-NGGw3TwAVudqd-XaLuA:-NGGw3TwAVudqd-XaLuB:bdvp1jp) ([raw file](https://github.com/eastgenomics/themis/blob/135e70ba7197ed9b3a2a8a33eb52abeeba4f3aeb/dxapp_compliance/Access_file_GH.py#L6)):*
> ```Python
> import os
> from ghapi.all import *
> from fastcore.all import *
> ```

be careful with wildcard imports, if any methods in side each of those are named the same the subsequent import will override them (and may override other package imports).
It's generally better to be specific (i.e. as you have done below for `jinja2`) or just import the package and if you don't like the name import as a your own prefix (i.e. `import pandas as pd`)



_Code quote:_
```Python
from ghapi.all import *
from fastcore.all import *
```
___
*[`dxapp_compliance/Access_file_GH.py` line 23 at r1](https://reviewable.io/reviews/eastgenomics/themis/4#-NGGww-Y3YW5kmYrHQBV:-NGGww-Y3YW5kmYrHQBW:bo9tmfk) ([raw file](https://github.com/eastgenomics/themis/blob/135e70ba7197ed9b3a2a8a33eb52abeeba4f3aeb/dxapp_compliance/Access_file_GH.py#L23)):*
> ```Python
>     Render jinja2 template with provided variables.
>     """
>     template = env.get_template("mytemplate.html")
> ```

where is `env` from?



_Code quote:_
```Python
env
```
___
*[`dxapp_compliance/Access_file_GH.py` line 28 at r1](https://reviewable.io/reviews/eastgenomics/themis/4#-NGGx2Xf9K-vbDzLUs-l:-NGGx2Xg2m2xoifR0mTj:bfcm7qw) ([raw file](https://github.com/eastgenomics/themis/blob/135e70ba7197ed9b3a2a8a33eb52abeeba4f3aeb/dxapp_compliance/Access_file_GH.py#L28)):*
> ```Python
> def get_credentials():
>     """
>     get_credentials
> ```

not needed?



_Code quote:_
```Python
get_credentials
```
___
*[`dxapp_compliance/Access_file_GH.py` line 49 at r1](https://reviewable.io/reviews/eastgenomics/themis/4#-NGGxH7U7MHwgTqSdNrS:-NGGxH7U7MHwgTqSdNrT:bfcm7qw) ([raw file](https://github.com/eastgenomics/themis/blob/135e70ba7197ed9b3a2a8a33eb52abeeba4f3aeb/dxapp_compliance/Access_file_GH.py#L49)):*
> ```Python
> class app_compliance:
>     """
>     app_compliance
> ```

not needed?



_Code quote:_
```Python
app_compliance
```
___
*[`dxapp_compliance/Access_file_GH.py` line 91 at r1](https://reviewable.io/reviews/eastgenomics/themis/4#-NGGxWqn6rK6qH9ofx9T:-NGGxWqn6rK6qH9ofx9U:b1obzjg) ([raw file](https://github.com/eastgenomics/themis/blob/135e70ba7197ed9b3a2a8a33eb52abeeba4f3aeb/dxapp_compliance/Access_file_GH.py#L91)):*
> ```Python
>             print(f"Correct only one region - {region_list[0]}")
>         else:
>             print(f"Incorrect multiple regions - {region_list}")
> ```

not necessarily correct, could be None or single non eu-central region



_Code quote:_
```Python
print(f"Incorrect multiple regions - {region_list}")
```
___
*[`dxapp_compliance/Access_file_GH.py` line 95 at r1](https://reviewable.io/reviews/eastgenomics/themis/4#-NGGy3K_8IlxFolU-Z94:-NGGy3KaAsKLBm4dyr4N:b-68clup) ([raw file](https://github.com/eastgenomics/themis/blob/135e70ba7197ed9b3a2a8a33eb52abeeba4f3aeb/dxapp_compliance/Access_file_GH.py#L95)):*
> ```Python
>         # Find source for app/applet and check compliance
>         src_file_contents, release_date, release_version = self.get_src_file(
>             app,
> ```

`app=app,` for consistency



_Code quote:_
```Python
app,
```
___
*[`dxapp_compliance/Access_file_GH.py` line 102 at r1](https://reviewable.io/reviews/eastgenomics/themis/4#-NGGywZwAWRO6G1xzZM_:-NGGywZwAWRO6G1xzZMa:b7fj2id) ([raw file](https://github.com/eastgenomics/themis/blob/135e70ba7197ed9b3a2a8a33eb52abeeba4f3aeb/dxapp_compliance/Access_file_GH.py#L102)):*
this is fine, just to be aware of some other options for less lines:
```
>>> e, f, g, h, = (None,) * 4
>>> print(e, f, g, h)
None None None None

>>> a = b = c = d = None
>>> print(a, b, c, d)
None None None None
```



_Code quote:_
```Python
        set_e_boolean, manual_compiling = None, None
        app_boolean, app_or_applet = None, None
        auth_devs_boolean, auth_users_boolean = None, None
```
___
*[`dxapp_compliance/Access_file_GH.py` line 123 at r1](https://reviewable.io/reviews/eastgenomics/themis/4#-NGGzyF09xtIlrGRFRfO:-NGGzyF09xtIlrGRFRfP:b4j1tal) ([raw file](https://github.com/eastgenomics/themis/blob/135e70ba7197ed9b3a2a8a33eb52abeeba4f3aeb/dxapp_compliance/Access_file_GH.py#L123)):*
> ```Python
>         if "set -e" in src_file_contents:
>             set_e_boolean = True
>         else:
> ```

I'd consider making each of these compliance checks there own fucntions as this is quite long now, ad if you want to check more things later on its just going to get bigger



_Code quote:_
```Python
        # src file compliance info.
        if "set -e" in src_file_contents:
            set_e_boolean = True
        else:
            set_e_boolean = False
        if "make install" in src_file_contents:
            no_manual_compiling = False
            # print(src_file_contents)
        else:
            no_manual_compiling = True
```
___
*[`dxapp_compliance/Access_file_GH.py` line 145 at r1](https://reviewable.io/reviews/eastgenomics/themis/4#-NGH-AdH8Na7aqVynrI-:-NGH-AdH8Na7aqVynrI0:blxdhgr) ([raw file](https://github.com/eastgenomics/themis/blob/135e70ba7197ed9b3a2a8a33eb52abeeba4f3aeb/dxapp_compliance/Access_file_GH.py#L145)):*
careful with chaining `.get()`, if any of the parent keys aren't present (i.e no `timeoutPolicy` is defined), you will get an error:
```
>>> d={'a': {'sub1': 1}}
>>> d.get('a').get('sub1')
1
>>> d.get('b').get('sub1')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'get'
```



_Suggestion:_
```Python
print(data.get('runSpec', {}).get('timeoutPolicy', {}).get('*', {}).get('hours'))```
```
___
*[`dxapp_compliance/Access_file_GH.py` line 161 at r1](https://reviewable.io/reviews/eastgenomics/themis/4#-NGH00P877WeTIzOa-48:-NGH00P877WeTIzOa-49:b1p8enb) ([raw file](https://github.com/eastgenomics/themis/blob/135e70ba7197ed9b3a2a8a33eb52abeeba4f3aeb/dxapp_compliance/Access_file_GH.py#L161)):*
> ```Python
>         print(data)
>         # print(data.get('runSpec', {}))
>         if authorised_users is None:
> ```

`if not authorised_users:` is more pythonic for checking truthyness



_Code quote:_
```Python
if authorised_users is None:
```
___
*[`dxapp_compliance/Access_file_GH.py` line 175 at r1](https://reviewable.io/reviews/eastgenomics/themis/4#-NGH0D-v0iCVme5X-Lls:-NGH0D-v0iCVme5X-Llt:b-3cbll7) ([raw file](https://github.com/eastgenomics/themis/blob/135e70ba7197ed9b3a2a8a33eb52abeeba4f3aeb/dxapp_compliance/Access_file_GH.py#L175)):*
> ```Python
> 
>         # regional options compliance info.
>         if region_list == ["aws:eu-central-1"]:
> ```

this might eventually change if we move to the new London data center, do you think this should be in the config?



_Code quote:_
```Python
["aws:eu-central-1"]
```
___
*[`dxapp_compliance/Access_file_GH.py` line 188 at r1](https://reviewable.io/reviews/eastgenomics/themis/4#-NGH0O_x3-TxzH-zQhQE:-NGH0O_x3-TxzH-zQhQF:b1ho5pc) ([raw file](https://github.com/eastgenomics/themis/blob/135e70ba7197ed9b3a2a8a33eb52abeeba4f3aeb/dxapp_compliance/Access_file_GH.py#L188)):*
> ```Python
>         name = data.get('name')
>         title = data.get('title')
>         if name is None:
> ```

`if not name`



_Code quote:_
```Python
if name is None:
```
___
*[`dxapp_compliance/Access_file_GH.py` line 511 at r1](https://reviewable.io/reviews/eastgenomics/themis/4#-NGH7XFBD-eJbRYqrPMN:-NGH7XFBD-eJbRYqrPMO:b-yegfka) ([raw file](https://github.com/eastgenomics/themis/blob/135e70ba7197ed9b3a2a8a33eb52abeeba4f3aeb/dxapp_compliance/Access_file_GH.py#L511)):*
> ```Python
>         """
>         list_of_compliance_scores = []
>         for _, [...]

2022-11-25 09:48 UTC, RSWilson1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/themis/4)* status: 1 of 4 files reviewed, 14 unresolved discussions (waiting on @jethror1 and @RSWilson1)

___
*[`dxapp_compliance/Access_file_GH.py` line 6 at r1](https://reviewable.io/reviews/eastgenomics/themis/4#-NGGw3TwAVudqd-XaLuA:-NHdwaXCA7GrTGrppzXO:bvje9qx) ([raw file](https://github.com/eastgenomics/themis/blob/135e70ba7197ed9b3a2a8a33eb52abeeba4f3aeb/dxapp_compliance/Access_file_GH.py#L6)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

be careful with wildcard imports, if any methods in side each of those are named the same the subsequent import will override them (and may override other package imports).
It's generally better to be specific (i.e. as you have done below for `jinja2`) or just import the package and if you don't like the name import as a your own prefix (i.e. `import pandas as pd`)
</blockquote></details>

Changed to specific imports except fastcore.all which requires wildcard import for ghapi.
___
*[`dxapp_compliance/Access_file_GH.py` line 23 at r1](https://reviewable.io/reviews/eastgenomics/themis/4#-NGGww-Y3YW5kmYrHQBV:-NHdwfx1-m9hpn4cRHV-:b-sxiafa) ([raw file](https://github.com/eastgenomics/themis/blob/135e70ba7197ed9b3a2a8a33eb52abeeba4f3aeb/dxapp_compliance/Access_file_GH.py#L23)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

where is `env` from?
</blockquote></details>

Added the code needed.
___
*[`dxapp_compliance/Access_file_GH.py` line 28 at r1](https://reviewable.io/reviews/eastgenomics/themis/4#-NGGx2Xf9K-vbDzLUs-l:-NHdwlhVE7Nobx_LUONb:b32ww0) ([raw file](https://github.com/eastgenomics/themis/blob/135e70ba7197ed9b3a2a8a33eb52abeeba4f3aeb/dxapp_compliance/Access_file_GH.py#L28)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

not needed?
</blockquote></details>

rm
___
*[`dxapp_compliance/Access_file_GH.py` line 49 at r1](https://reviewable.io/reviews/eastgenomics/themis/4#-NGGxH7U7MHwgTqSdNrS:-NHdwmfU0ULAQNPkr9yn:b32ww0) ([raw file](https://github.com/eastgenomics/themis/blob/135e70ba7197ed9b3a2a8a33eb52abeeba4f3aeb/dxapp_compliance/Access_file_GH.py#L49)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

not needed?
</blockquote></details>

rm
___
*[`dxapp_compliance/Access_file_GH.py` line 91 at r1](https://reviewable.io/reviews/eastgenomics/themis/4#-NGGxWqn6rK6qH9ofx9T:-NHdwnQv8e7cPuqzUgu2:bfpej6) ([raw file](https://github.com/eastgenomics/themis/blob/135e70ba7197ed9b3a2a8a33eb52abeeba4f3aeb/dxapp_compliance/Access_file_GH.py#L91)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

not necessarily correct, could be None or single non eu-central region
</blockquote></details>

Changed to handle more cases.
___
*[`dxapp_compliance/Access_file_GH.py` line 95 at r1](https://reviewable.io/reviews/eastgenomics/themis/4#-NGGy3K_8IlxFolU-Z94:-NHi41fu3oyBLfrLqewX:bb7f2mf) ([raw file](https://github.com/eastgenomics/themis/blob/135e70ba7197ed9b3a2a8a33eb52abeeba4f3aeb/dxapp_compliance/Access_file_GH.py#L95)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

`app=app,` for consistency
</blockquote></details>

done
___
*[`dxapp_compliance/Access_file_GH.py` line 102 at r1](https://reviewable.io/reviews/eastgenomics/themis/4#-NGGywZwAWRO6G1xzZM_:-NHi6olX6FVm-N_VN4jD:b-b5c35t) ([raw file](https://github.com/eastgenomics/themis/blob/135e70ba7197ed9b3a2a8a33eb52abeeba4f3aeb/dxapp_compliance/Access_file_GH.py#L102)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

this is fine, just to be aware of some other options for less lines:
```
>>> e, f, g, h, = (None,) * 4
>>> print(e, f, g, h)
None None None None

>>> a = b = c = d = None
>>> print(a, b, c, d)
None None None None
```
</blockquote></details>

changed.
___
*[`dxapp_compliance/Access_file_GH.py` line 123 at r1](https://reviewable.io/reviews/eastgenomics/themis/4#-NGGzyF09xtIlrGRFRfO:-NHdy9dyDNOS4T0ymm5-:b-qwzcsu) ([raw file](https://github.com/eastgenomics/themis/blob/135e70ba7197ed9b3a2a8a33eb52abeeba4f3aeb/dxapp_compliance/Access_file_GH.py#L123)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I'd consider making each of these compliance checks there own fucntions as this is quite long now, ad if you want to check more things later on its just going to get bigger
</blockquote></details>

refactored into new class
___
*[`dxapp_compliance/Access_file_GH.py` line 145 at r1](https://reviewable.io/reviews/eastgenomics/themis/4#-NGH-AdH8Na7aqVynrI-:-NHdyJ5D648PEKcfk1en:bgf4n8t) ([raw file](https://github.com/eastgenomics/themis/blob/135e70ba7197ed9b3a2a8a33eb52abeeba4f3aeb/dxapp_compliance/Access_file_GH.py#L145)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

careful with chaining `.get()`, if any of the parent keys aren't present (i.e no `timeoutPolicy` is defined), you will get an error:
```
>>> d={'a': {'sub1': 1}}
>>> d.get('a').get('sub1')
1
>>> d.get('b').get('sub1')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'get'
```
</blockquote></details>

Is there a good alternative to this? I thought by chaining and giving empty dictionaries would solve the chaining problem although it is a bit crude.
___
*[`dxapp_compliance/Access_file_GH.py` line 161 at r1](https://reviewable.io/reviews/eastgenomics/themis/4#-NGH00P877WeTIzOa-48:-NHi6ro-7DTAd8W1Yy4f:bb7f2mf) ([raw file](https://github.com/eastgenomics/themis/blob/135e70ba7197ed9b3a2a8a33eb52abeeba4f3aeb/dxapp_compliance/Access_file_GH.py#L161)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

`if not authorised_users:` is more pythonic for checking truthyness
</blockquote></details>

done
___
*[`dxapp_compliance/Access_file_GH.py` line 175 at r1](https://reviewable.io/reviews/eastgenomics/themis/4#-NGH0D-v0iCVme5X-Lls:-NHdyr2P11c9pztufI25:bfd98zk) ([raw file](https://github.com/eastgenomics/themis/blob/135e70ba7197ed9b3a2a8a33eb52abeeba4f3aeb/dxapp_compliance/Access_file_GH.py#L175)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

this might eventually change if we move to the new London data center, do you think this should be in the config?
</blockquote></details>

Yes would be better in a config
___
*[`dxapp_compliance/Access_file_GH.py` line 188 at r1](https://reviewable.io/reviews/eastgenomics/themis/4#-NGH0O_x3-TxzH-zQhQE:-NHe6cVI7JYkQ89QI7Rl:bb7f2mf) ([raw file](https://github.com/eastgenomics/themis/blob/135e70ba7197ed9b3a2a8a33eb52abeeba4f3aeb/dxapp_compliance/Access_file_GH.py#L188)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

`if not name`
</blockquote></details>

done



_Code quote:_
```Python
is None
```
___
*[`dxapp_compliance/Access_file_GH.py` line 511 at r1](https://reviewable.io/reviews/eastgenomics/themis/4#-NGH7XFBD-eJbRYqrPMN:-NHi6uNS-O2_e2DTwpbY:b-chptll) ([raw file](https://github.com/eastgenomics/themis/blob/135e70ba7197ed9b3a2a8a33eb52abeeba4f3aeb/dxapp_compliance/Access_file_GH.py#L511)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

whats going on here? seems confusing with no comments
</blockquote></details>

Added more comments and simplified.
___
*[`dxapp_compliance/Access_file_GH.py` line 535 at r1](https://reviewable.io/reviews/eastgenomics/themis/4#-NGH7bhM8O3CP795BfW_:-NHdyyavBtyGSkJSMtvi:b-hfpv0l) ([raw file](https://github.com/eastgenomics/themis/blob/135e70ba7197ed9b3a2a8a33eb52abeeba4f3aeb/dxapp_compliance/Access_file_GH.py#L535)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

not  [...]

2022-11-25 10:57 UTC, RSWilson1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/themis/4)* status: 1 of 4 files reviewed, 14 unresolved discussions (waiting on @jethror1 and @RSWilson1)

___
*[`dxapp_compliance/Access_file_GH.py` line 175 at r1](https://reviewable.io/reviews/eastgenomics/themis/4#-NGH0D-v0iCVme5X-Lls:-NHiQnrTC0JMVJDf0hxt:b-j3hzo0) ([raw file](https://github.com/eastgenomics/themis/blob/135e70ba7197ed9b3a2a8a33eb52abeeba4f3aeb/dxapp_compliance/Access_file_GH.py#L175)):*
<details><summary><i>Previously, RSWilson1 (Robert Wilson) wrote…</i></summary><blockquote>

Yes would be better in a config
</blockquote></details>

I have added this to the config


<!-- Sent from Reviewable.io -->

2022-11-25 11:30 UTC, jethror1 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/themis/4)* status: 1 of 4 files reviewed, 31 unresolved discussions (waiting on @RSWilson1)

___
*[`dxapp_compliance/Access_file_GH.py` line 145 at r1](https://reviewable.io/reviews/eastgenomics/themis/4#-NGH-AdH8Na7aqVynrI-:-NHiSe7m2EFXp8_kv-wo:bf5q716) ([raw file](https://github.com/eastgenomics/themis/blob/135e70ba7197ed9b3a2a8a33eb52abeeba4f3aeb/dxapp_compliance/Access_file_GH.py#L145)):*
<details><summary><i>Previously, RSWilson1 (Robert Wilson) wrote…</i></summary><blockquote>

Is there a good alternative to this? I thought by chaining and giving empty dictionaries would solve the chaining problem although it is a bit crude.
</blockquote></details>

nope that's a nice solution :)
___
*[`dxapp_compliance/Access_file_GH.py` line 161 at r1](https://reviewable.io/reviews/eastgenomics/themis/4#-NGH00P877WeTIzOa-48:-NHiT2nDEoSfHnjPiKZ3:b-9mm0di) ([raw file](https://github.com/eastgenomics/themis/blob/135e70ba7197ed9b3a2a8a33eb52abeeba4f3aeb/dxapp_compliance/Access_file_GH.py#L161)):*
<details><summary><i>Previously, RSWilson1 (Robert Wilson) wrote…</i></summary><blockquote>

done
</blockquote></details>

can shorten to:
```
if authorised_users == ['org-emee_1']:
    auth_users_boolean = True
else:
    auth_users_boolean = False

```
___
*[`dxapp_compliance/Access_file_GH.py` line 511 at r1](https://reviewable.io/reviews/eastgenomics/themis/4#-NHiXi_KA54N6YzQWAAA:-NHiXi_KA54N6YzQWAAB:bp1g50e) ([raw file](https://github.com/eastgenomics/themis/blob/135e70ba7197ed9b3a2a8a33eb52abeeba4f3aeb/dxapp_compliance/Access_file_GH.py#L511)):*
in general its best to try avoid using `.iterrows()` as its pretty slow (and there's generally better ways to write things if you end up iterating over a df).

Example of how to do the first part:
```
# example dataframe
>>> df = pd.DataFrame([{'app': 'app-1', 'interpreter': 'bash'}, {'app': 'app-2', 'interpreter': 'python'}])
>>> df
     app interpreter
0  app-1        bash
1  app-2      python

>>> df['total_performa'] = df['interpreter'].apply(lambda x: 10 if 'bash' in x else 9)
>>> df
     app interpreter  total_performa
0  app-1        bash              10
1  app-2      python               9
```

The rest is kind of hard to suggest without seeing the dataframe, if you add an example of what it looks like I can suggest more :) 



_Code quote:_
```Python
compliance_df.iterrows():
```
___
*[`dxapp_compliance/Access_file_GH.py` line 51 at r3](https://reviewable.io/reviews/eastgenomics/themis/4#-NHiJyU12RB_5kY_2luQ:-NHiJyU12RB_5kY_2luR:b-5ygios) ([raw file](https://github.com/eastgenomics/themis/blob/aa561aab915672e64ae218c763a390d542f26367/dxapp_compliance/Access_file_GH.py#L51)):*
> ```Python
>                         ):
>     """
>     Render jinja2 template with provided variables.
> ```

doc string args and return/output missing, I'd recommend autodoc extension if you're not already using it



_Code quote:_
```Python
Render jinja2 template with provided variables.
```
___
*[`dxapp_compliance/Access_file_GH.py` line 88 at r3](https://reviewable.io/reviews/eastgenomics/themis/4#-NHiKDzf1QUTKFVA3w9A:-NHiKDzf1QUTKFVA3w9B:b-npfeua) ([raw file](https://github.com/eastgenomics/themis/blob/aa561aab915672e64ae218c763a390d542f26367/dxapp_compliance/Access_file_GH.py#L88)):*
> ```Python
>     organisation (str):
>         Organisation dnanexus username.
> ```

missing default region return
___
*[`dxapp_compliance/Access_file_GH.py` line 110 at r3](https://reviewable.io/reviews/eastgenomics/themis/4#-NHiKPFvE62IHoJlkS9c:-NHiKPFvE62IHoJlkS9d:boghxok) ([raw file](https://github.com/eastgenomics/themis/blob/aa561aab915672e64ae218c763a390d542f26367/dxapp_compliance/Access_file_GH.py#L110)):*
> ```Python
>                   default_region=None,):
>         """
>         check_all compliance measures.
> ```

more detail please + describe args/returns



_Code quote:_
```Python
check_all compliance measures.
```
___
*[`dxapp_compliance/Access_file_GH.py` line 128 at r3](https://reviewable.io/reviews/eastgenomics/themis/4#-NHiKuqO2pHLaYyRYXCy:-NHiKuqO2pHLaYyRYXCz:ble9zdu) ([raw file](https://github.com/eastgenomics/themis/blob/aa561aab915672e64ae218c763a390d542f26367/dxapp_compliance/Access_file_GH.py#L128)):*
you don't need to check if the list only has one element, can be still looped over as below:
```
>>> l1 = ['a']
>>> l2 = ['a', 'b', 'c']
>>> for x in l1:
...     print(x)
... 
a
>>> for x in l2:
...     print(x)
... 
a
b
c
```

this whole block including the final else though can be simplified to `regions = [x.split(':')[1].rstrip("']") for x in region_list]`
```
>>> l1=[]
>>> l2=["aws:eu-central-1']"]
>>> l3=["aws:eu-central-1']", "aws:eu-central-2']", "aws:eu-central-3']"]

>>> [x.split(':')[1].rstrip("']") for x in l1]
[]
>>> [x.split(':')[1].rstrip("']") for x in l2]
['eu-central-1']
>>> [x.split(':')[1].rstrip("']") for x in l3]
['eu-central-1', 'eu-central-2', 'eu-central-3']
```



_Code quote:_
```Python
        if len(region_list) == 1:
            region_list = region_list[0]
            regions = region_list.split(":")[1].rstrip("']")
        elif len(region_list) > 1:
            regions = []
            for region in region_list:
                region_str = region.split(":")[1].rstrip("']")
                regions.append(region_str)
```
___
*[`dxapp_compliance/Access_file_GH.py` line 169 at r3](https://reviewable.io/reviews/eastgenomics/themis/4#-NHiMF1N6AimG1ScteFP:-NHiMF1N6AimG1ScteFQ:b-58so6z) ([raw file](https://github.com/eastgenomics/themis/blob/aa561aab915672e64ae218c763a390d542f26367/dxapp_compliance/Access_file_GH.py#L169)):*
> ```Python
> 
>         details_dict = {'name': name,
>                         # 'release_version': data.get('properties', {}).get(),
> ```

needed?



_Code quote:_
```Python
# 'release_version': data.get('properties', {}).get(),
```
___
*[`dxapp_compliance/Access_file_GH.py` line 184 at r3](https://reviewable.io/reviews/eastgenomics/themis/4#-NHiMGs52k8yOOTEq0JG:-NHiMGs52k8yOOTEq0JH:b-58so6z) ([raw file](https://github.com/eastgenomics/themis/blob/aa561aab915672e64ae218c763a390d542f26367/dxapp_compliance/Access_file_GH.py#L184)):*
> ```Python
>                         'latest_commit_date': latest_commit_date,
>                         'timeout_setting': timeout_setting,
>                         # 'description': data.get('summary'),
> ```

needed?



_Code quote:_
```Python
# 'description': data.get('summary'),
```
___
*[`dxapp_compliance/Access_file_GH.py` line 216 at r3](https://reviewable.io/reviews/eastgenomics/themis/4#-NHiMUz_0THGvjjx2uu9:-NHiMUz_0THGvjjx2uuA:b-4gykmk) ([raw file](https://github.com/eastgenomics/themis/blob/aa561aab915672e64ae218c763a390d542f26367/dxapp_compliance/Access_file_GH.py#L216)):*
> ```Python
>         if region_list is [default_region]:
>             correct_regional_boolean = True
>             region_options_num = num_regions
> ```

you assign this in every conditional part then return it, can it just be removed and return `num_regions`?



_Code quote:_
```Python
region_options_num = num_regions
```
___
*[`dxapp_compliance/Access_file_GH.py` line 233 at r3](https://reviewable.io/reviews/eastgenomics/themis/4#-NHiMkahC7quKR90e0k4:-NHiMkahC7quKR90e0k5:b-stsb1e) ([raw file](https://github.com/eastgenomics/themis/blob/aa561aab915672e64ae218c763a390d542f26367/dxapp_compliance/Access_file_GH.py#L233)):*
> ```Python
>             logger.info(
>                 "Incorrect regional option set and multiple regions present.")
> ```

this whole above block could be simplified down to:
```
if region_list is [default_region] or 'aws:eu-central-1' in region_list:
    correct_regional_boolean = True
elif region_list is [] or elif num_regions == 1:
    correct_regional_boolean = False
    logger.info("Incorrect regional option set.")
else:
    correct_regional_boolean = False
    logger.info("Incorrect regional option set and multiple regions present.")

```
___
*[`dxapp_compliance/Access_file_GH.py` li [...]

2022-11-25 11:38 UTC, jethror1 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/themis/4)* status: 1 of 4 files reviewed, 38 unresolved discussions (waiting on @RSWilson1)

___
*[`dxapp_compliance/Access_file_GH.py` line 871 at r3](https://reviewable.io/reviews/eastgenomics/themis/4#-NHiYjRs7QCli_coSmDO:-NHiYjRs7QCli_coSmDP:bhj67rt) ([raw file](https://github.com/eastgenomics/themis/blob/aa561aab915672e64ae218c763a390d542f26367/dxapp_compliance/Access_file_GH.py#L871)):*
> ```Python
>             list_of_branches = api.repos.list_branches(
>                 organisation_name, repo_name)
>         except HTTP404NotFoundError:
> ```

is it possible to have a repo with no branches?



_Code quote:_
```Python
except HTTP404NotFoundError:
```
___
*[`dxapp_compliance/Access_file_GH.py` line 876 at r3](https://reviewable.io/reviews/eastgenomics/themis/4#-NHiYqLm4FJnTTvsKEmY:-NHiYqLm4FJnTTvsKEmZ:byg0uma) ([raw file](https://github.com/eastgenomics/themis/blob/aa561aab915672e64ae218c763a390d542f26367/dxapp_compliance/Access_file_GH.py#L876)):*
> ```Python
> 
>         # Find sha for each branch and append to list for api calls.
>         for branch in list_of_branches:
> ```

list_of_shas = [branch['commit']['sha'] for branch in list_of_branches]



_Code quote:_
```Python
        for branch in list_of_branches:
            sha = branch['commit']['sha']
            list_of_shas.append(sha)
```
___
*[`dxapp_compliance/Access_file_GH.py` line 880 at r3](https://reviewable.io/reviews/eastgenomics/themis/4#-NHiYzFFAKv1qO-EePu_:-NHiYzFFAKv1qO-EePua:b-58so6z) ([raw file](https://github.com/eastgenomics/themis/blob/aa561aab915672e64ae218c763a390d542f26367/dxapp_compliance/Access_file_GH.py#L880)):*
> ```Python
>             list_of_shas.append(sha)
> 
>         # For branch in branches
> ```

needed?



_Code quote:_
```Python
# For branch in branches
```
___
*[`dxapp_compliance/Access_file_GH.py` line 905 at r3](https://reviewable.io/reviews/eastgenomics/themis/4#-NHiZ5ia5EMYBbkV49ZF:-NHiZ5ia5EMYBbkV49ZG:blu00u9) ([raw file](https://github.com/eastgenomics/themis/blob/aa561aab915672e64ae218c763a390d542f26367/dxapp_compliance/Access_file_GH.py#L905)):*
> ```Python
>         This calls the functions to get the compliance and then creates the dfs.
> 
>         Parameters
> ```

missing list_apps param
___
*[`dxapp_compliance/Access_file_GH.py` line 919 at r3](https://reviewable.io/reviews/eastgenomics/themis/4#-NHiZBoM4X9d60rg3QJ1:-NHiZBoM4X9d60rg3QJ2:b-qiz3j4) ([raw file](https://github.com/eastgenomics/themis/blob/aa561aab915672e64ae218c763a390d542f26367/dxapp_compliance/Access_file_GH.py#L919)):*
> ```Python
>         compliance_df = details_df = None
>         if len(list_apps) != len(list_of_json_contents):
>             print("Error missing repos")
> ```

do we just want to print an error or do something here?



_Code quote:_
```Python
print("Error missing repos")
```
___
*[`dxapp_compliance/Access_file_GH.py` line 920 at r3](https://reviewable.io/reviews/eastgenomics/themis/4#-NHiZGE82KrIzQFEI_Pk:-NHiZGE91FpoRfZ7uRIS:b-c4r1zq) ([raw file](https://github.com/eastgenomics/themis/blob/aa561aab915672e64ae218c763a390d542f26367/dxapp_compliance/Access_file_GH.py#L920)):*
> ```Python
>         if len(list_apps) != len(list_of_json_contents):
>             print("Error missing repos")
>         else:
> ```

this is redundant since it will continue if the above is not true



_Code quote:_
```Python
        else:
            pass
```
___
*[`dxapp_compliance/Access_file_GH.py` line 1020 at r3](https://reviewable.io/reviews/eastgenomics/themis/4#-NHiZsEa7b0YDJQFtP2h:-NHiZsEa7b0YDJQFtP2i:bxjwidq) ([raw file](https://github.com/eastgenomics/themis/blob/aa561aab915672e64ae218c763a390d542f26367/dxapp_compliance/Access_file_GH.py#L1020)):*
> ```Python
>                 pandas dataframe of csv file with minor changes.
>         """
>         df = pd.read_csv(path_to_dataframe)
> ```

 you write to a file and then read back in to plot? can the df not be directly passed?


<!-- Sent from Reviewable.io -->

2022-11-29 15:44 UTC, RSWilson1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/themis/4)* status: 1 of 4 files reviewed, 38 unresolved discussions (waiting on @jethror1 and @RSWilson1)

___
*[`dxapp_compliance/Access_file_GH.py` line 145 at r1](https://reviewable.io/reviews/eastgenomics/themis/4#-NGH-AdH8Na7aqVynrI-:-NHxWaokCvquT0Q_p6S1:b-896fix) ([raw file](https://github.com/eastgenomics/themis/blob/135e70ba7197ed9b3a2a8a33eb52abeeba4f3aeb/dxapp_compliance/Access_file_GH.py#L145)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

nope that's a nice solution :)
</blockquote></details>

Done.
___
*[`dxapp_compliance/Access_file_GH.py` line 161 at r1](https://reviewable.io/reviews/eastgenomics/themis/4#-NGH00P877WeTIzOa-48:-NHxY_Hl53bPjC1g3erm:bfiyzvm) ([raw file](https://github.com/eastgenomics/themis/blob/135e70ba7197ed9b3a2a8a33eb52abeeba4f3aeb/dxapp_compliance/Access_file_GH.py#L161)):*
> if authorised_users == ['org-emee_1']:
>     auth_users_boolean = True
> else:
>     auth_users_boolean = False
done
___
*[`dxapp_compliance/Access_file_GH.py` line 511 at r1](https://reviewable.io/reviews/eastgenomics/themis/4#-NHiXi_KA54N6YzQWAAA:-NHy_NlX3xhLLHReyFcA:b-vliybm) ([raw file](https://github.com/eastgenomics/themis/blob/135e70ba7197ed9b3a2a8a33eb52abeeba4f3aeb/dxapp_compliance/Access_file_GH.py#L511)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

in general its best to try avoid using `.iterrows()` as its pretty slow (and there's generally better ways to write things if you end up iterating over a df).

Example of how to do the first part:
```
# example dataframe
>>> df = pd.DataFrame([{'app': 'app-1', 'interpreter': 'bash'}, {'app': 'app-2', 'interpreter': 'python'}])
>>> df
     app interpreter
0  app-1        bash
1  app-2      python

>>> df['total_performa'] = df['interpreter'].apply(lambda x: 10 if 'bash' in x else 9)
>>> df
     app interpreter  total_performa
0  app-1        bash              10
1  app-2      python               9
```

The rest is kind of hard to suggest without seeing the dataframe, if you add an example of what it looks like I can suggest more :) 
</blockquote></details>

yep I have changed to not use iterrows.
___
*[`dxapp_compliance/Access_file_GH.py` line 51 at r3](https://reviewable.io/reviews/eastgenomics/themis/4#-NHiJyU12RB_5kY_2luQ:-NHjVlak75k4Nr5rEDPo:btthtrr) ([raw file](https://github.com/eastgenomics/themis/blob/aa561aab915672e64ae218c763a390d542f26367/dxapp_compliance/Access_file_GH.py#L51)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

doc string args and return/output missing, I'd recommend autodoc extension if you're not already using it
</blockquote></details>

Added and yes I am using autodoc, although I need to configure it properly.
___
*[`dxapp_compliance/Access_file_GH.py` line 88 at r3](https://reviewable.io/reviews/eastgenomics/themis/4#-NHiKDzf1QUTKFVA3w9A:-NHjVk7g9Q37nV8MdyOw:b-8b11j9) ([raw file](https://github.com/eastgenomics/themis/blob/aa561aab915672e64ae218c763a390d542f26367/dxapp_compliance/Access_file_GH.py#L88)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

missing default region return
</blockquote></details>

Added
___
*[`dxapp_compliance/Access_file_GH.py` line 110 at r3](https://reviewable.io/reviews/eastgenomics/themis/4#-NHiKPFvE62IHoJlkS9c:-NHj_yL2A03jIUw3so5C:b-8b11j9) ([raw file](https://github.com/eastgenomics/themis/blob/aa561aab915672e64ae218c763a390d542f26367/dxapp_compliance/Access_file_GH.py#L110)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

more detail please + describe args/returns
</blockquote></details>

Added
___
*[`dxapp_compliance/Access_file_GH.py` line 128 at r3](https://reviewable.io/reviews/eastgenomics/themis/4#-NHiKuqO2pHLaYyRYXCy:-NHybpQX1ih_3KnO3J8R:b-smebhf) ([raw file](https://github.com/eastgenomics/themis/blob/aa561aab915672e64ae218c763a390d542f26367/dxapp_compliance/Access_file_GH.py#L128)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

you don't need to check if the list only has one element, can be still looped over as below:
```
>>> l1 = ['a']
>>> l2 = ['a', 'b', 'c']
>>> for x in l1:
...     print(x)
... 
a
>>> for x in l2:
...     print(x)
... 
a
b
c
```

this whole block including the final else though can be simplified to `regions = [x.split(':')[1].rstrip("']") for x in region_list]`
```
>>> l1=[]
>>> l2=["aws:eu-central-1']"]
>>> l3=["aws:eu-central-1']", "aws:eu-central-2']", "aws:eu-central-3']"]

>>> [x.split(':')[1].rstrip("']") for x in l1]
[]
>>> [x.split(':')[1].rstrip("']") for x in l2]
['eu-central-1']
>>> [x.split(':')[1].rstrip("']") for x in l3]
['eu-central-1', 'eu-central-2', 'eu-central-3']
```
</blockquote></details>

changed to list comp
___
*[`dxapp_compliance/Access_file_GH.py` line 169 at r3](https://reviewable.io/reviews/eastgenomics/themis/4#-NHiMF1N6AimG1ScteFP:-NHja8hAByoPVU0xeeh7:bb7lgjf) ([raw file](https://github.com/eastgenomics/themis/blob/aa561aab915672e64ae218c763a390d542f26367/dxapp_compliance/Access_file_GH.py#L169)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

needed?
</blockquote></details>

nope
___
*[`dxapp_compliance/Access_file_GH.py` line 184 at r3](https://reviewable.io/reviews/eastgenomics/themis/4#-NHiMGs52k8yOOTEq0JG:-NHja9fhEaIb40TnOkru:bb7lgjf) ([raw file](https://github.com/eastgenomics/themis/blob/aa561aab915672e64ae218c763a390d542f26367/dxapp_compliance/Access_file_GH.py#L184)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

needed?
</blockquote></details>

nope
___
*[`dxapp_compliance/Access_file_GH.py` line 216 at r3](https://reviewable.io/reviews/eastgenomics/themis/4#-NHiMUz_0THGvjjx2uu9:-NHxWGiUBdfS7X8vAz2T:b-9vt4w8) ([raw file](https://github.com/eastgenomics/themis/blob/aa561aab915672e64ae218c763a390d542f26367/dxapp_compliance/Access_file_GH.py#L216)):*
> regions = [x.split(':')[1].rstrip("']") for x in region_list]
Yep changed to num_regions only.
___
*[`dxapp_compliance/Access_file_GH.py` line 233 at r3](https://reviewable.io/reviews/eastgenomics/themis/4#-NHiMkahC7quKR90e0k4:-NHjcmPs68ht_5QN5ztB:bgg42ki) ([raw file](https://github.com/eastgenomics/themis/blob/aa561aab915672e64ae218c763a390d542f26367/dxapp_compliance/Access_file_GH.py#L233)):*
> if region_list is [default_region] or 'aws:eu-central-1' in region_list:
>     correct_regional_boolean = True
> elif region_list is [] or elif num_regions == 1:
>     correct_regional_boolean = False
>     logger.info("Incorrect regional option set.")
> else:
>     correct_regional_boolean = False
>     logger.info("Incorrect regional option set and multiple regions present.")
Yep changed with a few tweaks.
___
*[`dxapp_compliance/Access_file_GH.py` line 249 at r3](https://reviewable.io/reviews/eastgenomics/themis/4#-NHiNSUT8iKqAAn73qGa:-NHjf5cF36Wo44ElXnr5:b5p94p3) ([raw file](https://github.com/eastgenomics/themis/blob/aa561aab915672e64ae218c763a390d542f26367/dxapp_compliance/Access_file_GH.py#L249)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

this copied from above?
</blockquote></details>

changed to relevant function
___
*[`dxapp_compliance/Access_file_GH.py` line 259 at r3](https://reviewable.io/reviews/eastgenomics/themis/4#-NHiNfVn32Nn43SDdWSG:-NHxWYNgA45QGsmmciVA:bgl1q2r) ([raw file](https://github.com/eastgenomics/themis/blob/aa561aab915672e64ae218c763a390d542f26367/dxapp_compliance/Access_file_GH.py#L259)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

this can just be `if not timeout_policy_dict` as empty objects evaluate to false:
```
>>> d={}
>>> if d:
...     print('y')
... else:
...     print('n')
... 
n
```

you can also write simple conditional assignments l [...]

2022-11-30 12:49 UTC, jethror1 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/themis/4)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @RSWilson1)

___
*[`dxapp_compliance/Access_file_GH.py` line 51 at r3](https://reviewable.io/reviews/eastgenomics/themis/4#-NHiJyU12RB_5kY_2luQ:-NI7SQ0n8xL30B5CnZ79:bf7r6xd) ([raw file](https://github.com/eastgenomics/themis/blob/aa561aab915672e64ae218c763a390d542f26367/dxapp_compliance/Access_file_GH.py#L51)):*
<details><summary><i>Previously, RSWilson1 (Robert Wilson) wrote…</i></summary><blockquote>

Added and yes I am using autodoc, although I need to configure it properly.
</blockquote></details>

do you need help configuring it?
___
*[`dxapp_compliance/Access_file_GH.py` line 670 at r3](https://reviewable.io/reviews/eastgenomics/themis/4#-NHiVY8u-LpK6bVKBN6w:-NI7YGa-BcIy-3zP3CX2:b-6k1j7f) ([raw file](https://github.com/eastgenomics/themis/blob/aa561aab915672e64ae218c763a390d542f26367/dxapp_compliance/Access_file_GH.py#L670)):*
this can be done together with `re.search(r'(.py|.sh)$', content['name'])`:
```
>>> import glob
>>> import re
>>> files = glob.glob("**/*", recursive=True)
>>> files
['file2.sh', 'file3.json', 'file1.py']
>>> for file in files:
...     if re.search(r'(.py|.sh)$', file):
...             print(file)
... 
file2.sh
file1.py
```

using `$` with regex only matches the pattern against the end of the string so ideal for finding file extensions, then `( )` matches the whole pattern inside and `|`  can be added for multiple patterns
___
*[`dxapp_compliance/Access_file_GH.py` line 919 at r3](https://reviewable.io/reviews/eastgenomics/themis/4#-NHiZBoM4X9d60rg3QJ1:-NI7ZTfx-cDW1VPWUUXb:bqo0st2) ([raw file](https://github.com/eastgenomics/themis/blob/aa561aab915672e64ae218c763a390d542f26367/dxapp_compliance/Access_file_GH.py#L919)):*
a zero exit code is success, you would be better not defining one (iirc the default is 1 which is generic error).

Another thing you can do is raise errors yourself manually instead of using `sys.exit` if you want to be specific about the type of error.

Here are the ones available: https://docs.python.org/3/library/exceptions.html

example: 
```
>>> if 1 != 2:
...     raise AssertionError('they dont match')
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
AssertionError: they dont match
```
___
*[`dxapp_compliance/Access_file_GH.py` line 73 at r4](https://reviewable.io/reviews/eastgenomics/themis/4#-NI7ThuF4yDKU5n2vTRb:-NI7ThuF4yDKU5n2vTRc:bjmlsk2) ([raw file](https://github.com/eastgenomics/themis/blob/8e4c5a91bed9d3890500266e6631b307a589ce38/dxapp_compliance/Access_file_GH.py#L73)):*
> ```Python
>     -------
>     None
>     But writes html file of the report with provided variables.
> ```

its not in the numpy style guide but I like to add files written under an Outputs section, something like (then Returns isn't needed if its empty):
```
Outputs
-----------
.html
    HTML report of all app compliance
```



_Suggestion:_
```Python
ut writes html file of the report with provided variables.   
```
___
*[`dxapp_compliance/templates/base.html` line 0 at r4](https://reviewable.io/reviews/eastgenomics/themis/4#-NI7_SEf6Nkx21LEqEC4:-NI7_SEf6Nkx21LEqEC5:b-58so6z) ([raw file](https://github.com/eastgenomics/themis/blob/ad218b6ced627856469304620ce1d5ff3b85da5a/dxapp_compliance/templates/base.html#L0)):*
needed?


<!-- Sent from Reviewable.io -->

2022-12-01 15:58 UTC, RSWilson1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/themis/4)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @jethror1 and @RSWilson1)

___
*[`dxapp_compliance/Access_file_GH.py` line 51 at r3](https://reviewable.io/reviews/eastgenomics/themis/4#-NHiJyU12RB_5kY_2luQ:-NICttjr4rnC8Q2gmsbT:b-curxj9) ([raw file](https://github.com/eastgenomics/themis/blob/aa561aab915672e64ae218c763a390d542f26367/dxapp_compliance/Access_file_GH.py#L51)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

do you need help configuring it?
</blockquote></details>

do you have an example config?
___
*[`dxapp_compliance/Access_file_GH.py` line 670 at r3](https://reviewable.io/reviews/eastgenomics/themis/4#-NHiVY8u-LpK6bVKBN6w:-NICtbN-0LJ9claDTS0Y:b-elsj80) ([raw file](https://github.com/eastgenomics/themis/blob/aa561aab915672e64ae218c763a390d542f26367/dxapp_compliance/Access_file_GH.py#L670)):*
> re.search(r'(.py|.sh)$', content['name'])
Nice, done!
___
*[`dxapp_compliance/Access_file_GH.py` line 919 at r3](https://reviewable.io/reviews/eastgenomics/themis/4#-NHiZBoM4X9d60rg3QJ1:-NICtryT0H4ZV0T-7y-o:b-vyty90) ([raw file](https://github.com/eastgenomics/themis/blob/aa561aab915672e64ae218c763a390d542f26367/dxapp_compliance/Access_file_GH.py#L919)):*
> raise AssertionError('they dont match')
done
___
*[`dxapp_compliance/Access_file_GH.py` line 73 at r4](https://reviewable.io/reviews/eastgenomics/themis/4#-NI7ThuF4yDKU5n2vTRb:-NIDP6lo256TlWNjMQAr:b-fdwsth) ([raw file](https://github.com/eastgenomics/themis/blob/8e4c5a91bed9d3890500266e6631b307a589ce38/dxapp_compliance/Access_file_GH.py#L73)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

its not in the numpy style guide but I like to add files written under an Outputs section, something like (then Returns isn't needed if its empty):
```
Outputs
-----------
.html
    HTML report of all app compliance
```
</blockquote></details>

Yep added, that makes it much clearer
___
*[`dxapp_compliance/templates/base.html` line  at r4](https://reviewable.io/reviews/eastgenomics/themis/4#-NI7_SEf6Nkx21LEqEC4:-NI7cAvd0X_kSfiAz-_S:b-tqbcfi) ([raw file](https://github.com/eastgenomics/themis/blob/ad218b6ced627856469304620ce1d5ff3b85da5a/dxapp_compliance/templates/base.html#L)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

needed?
</blockquote></details>

Nope, I wanted to use it and extend but never got round to it.


<!-- Sent from Reviewable.io -->

2022-12-02 11:23 UTC, jethror1 requested changes
> Reviewed 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/themis/4)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @RSWilson1)

___
*[`dxapp_compliance/Access_file_GH.py` line 51 at r3](https://reviewable.io/reviews/eastgenomics/themis/4#-NHiJyU12RB_5kY_2luQ:-NIHZbGu-XHe4PnLlCyP:b-aktxii) ([raw file](https://github.com/eastgenomics/themis/blob/aa561aab915672e64ae218c763a390d542f26367/dxapp_compliance/Access_file_GH.py#L51)):*
<details><summary><i>Previously, RSWilson1 (Robert Wilson) wrote…</i></summary><blockquote>

do you have an example config?
</blockquote></details>

I just have mine set to numpy, will send you a screenshot on slack


<!-- Sent from Reviewable.io -->

2022-12-14 10:17 UTC, merged